CLUSTER-5. bento-cluster should not start if any ports are taken.
This commit modifies bento-cluster so that it does not start if any of the
configured ports are taken. To facilitate this, a new tool was added which
checks that all the ports are open. If the check fails, the bento script refuses
to start the clusters.

Signed-off-by: Aaron Kimball <aaron@wibidata.com>

diff --git a/src/main/scripts/bento b/src/main/scripts/bento
--- a/src/main/scripts/bento
+++ b/src/main/scripts/bento
@@ -389,11 +389,20 @@ fi
 
 # Start the mini cluster.
 if $start_cluster ; then
+  # Check if bento-cluster is already running.
   if [ -e "${BENTO_PID_FILE}" ]; then
     echo "PID file already exists at ${BENTO_PID_FILE}"
     echo "Stop bento-cluster or remove stale PID file before trying to start cluster again."
     exit 1
   fi
+
+  # Check if bento-cluster's ports are open.
+  java -cp "$bento_cp" $java_opts $BENTO_JAVA_OPTS org.kiji.bento.tools.PortCheckingTool
+  if [[ "$?" != "0" ]]; then
+    echo "Port check failed. Not starting bento-cluster."
+    exit 1
+  fi
+
   echo "Starting bento-cluster..."
 
   class=org.kiji.bento.tools.MiniClusterTool
