CLUSTER-19. CLUSTER-7 breaks bento-cluster on Mac OS X.
The DNS checker tool (which ensures both localhost and the machine's hostname
resolve to the same IP and refuses to start bento-cluster if this is not the
case) does not function correctly on Mac OS X. This check is designed to avoid
a common problem on Ubuntu machines. This commit modifies the bento script so
that the DNS check is not performed on Mac OS X, so that bento-cluster again
functions correctly on those systems.

Signed-off-by: Chad Metcalf <chad@wibidata.com>

diff --git a/src/main/scripts/bento b/src/main/scripts/bento
--- a/src/main/scripts/bento
+++ b/src/main/scripts/bento
@@ -217,12 +217,16 @@ function mutate_classpath () {
 
 function check_host_configuration() {
   # Check if the IP address of the local machine can be resolved.
-  java -cp "$bento_cp" $java_opts $BENTO_JAVA_OPTS \
-    org.kiji.bento.tools.DNSCheckingTool "--hostname=$(hostname)"
+  # Skip this check on Mac OS X as it does not behave correctly on Mac systems,
+  # and the check is primarily made to detect a problem on Ubuntu.
+  if [ `uname` != "Darwin" ]; then
+    java -cp "$bento_cp" $java_opts $BENTO_JAVA_OPTS \
+      org.kiji.bento.tools.DNSCheckingTool "--hostname=$(hostname)"
 
-  if [[ "$?" != "0" ]]; then
-    echo "Local DNS check failed.  Please resolve and try again."
-    exit 1
+    if [[ "$?" != "0" ]]; then
+      echo "Local DNS check failed.  Please resolve and try again."
+      exit 1
+    fi
   fi
 }
 
@@ -434,7 +438,7 @@ if $start_cluster ; then
   check_host_configuration
 
   # Check if bento-cluster's ports are open.
-  java -cp "$bento_cp" $java_opts $BENTO_JAVA_OPTS org.kiji.bento.tools.PortCheckingTool 
+  java -cp "$bento_cp" $java_opts $BENTO_JAVA_OPTS org.kiji.bento.tools.PortCheckingTool
   if [[ "$?" != "0" ]]; then
     echo "Port check failed. Not starting bento-cluster."
     exit 1
